name = "instant-style"  # 你的项目名称
type = "javascript"     # 或 "webpack", "rust", etc. 取决于你的项目类型
workers_dev = true       # 是否在 Workers Dev 环境中运行
route = ""              # 可选：指定一个路由规则
zone_id = ""            # 可选：指定一个 Zone ID
account_id = "a295b6282fcb8e6e3dc96abfbb78a48e"  # 你的 Cloudflare 账户 ID
